name: Build

on: [ push, pull_request ]

jobs:
  build-mirai:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: # mirai build requires a minimum system memory of 8 GB, while Windows and Ubuntu VMs provides only 7 GB. See https://github.com/mamoe/mirai/actions/runs/1608172113 for details.
#          - windows-latest
          - macos-11
#          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Init gradle project
        run: ./gradlew clean --scan

      - name: Build all
        run: ./gradlew assemble --scan

      - name: Upload build directory
        uses: actions/upload-artifact@main
        with:
          name: build${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: /Users/runner/work/mirai/mirai/mirai-core/build/libs/

      - name: Upload All to cowtransfer
        id: cowtransfer
        run: |
          brew install zip
          zip -r -9 ../mirai.zip ../mirai
          curl -fsSL git.io/file-transfer | sh
          ./transfer cow --block 2621440 -s -p 64 --no-progress ../mirai.zip 2>&1 | tee cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
          echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
